{
 "title": "DIC-Monitor",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result( max(increase(dic_http_request_total{job=\"$application\"}[$__range])) by (instance))"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "系统信息", "type": "text", "gridPos": { "h": 1, "w": 5, "x": 0, "y": 1 } },
  { "title": "应用信息", "type": "text", "gridPos": { "h": 1, "w": 19, "x": 5, "y": 1 } },
  {
   "title": "系统运行时间",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "instance_uptime{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processor（核）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "processors{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "启动时间",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 2 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() * 1000 - instance_uptime{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM总内存",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 2 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "JVM内存使用",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 2 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_free{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "空闲"
    },
    {
     "expr": "heap_used{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "堆"
    },
    {
     "expr": "nonheap_used{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "非堆"
    }
   ]
  },
  {
   "title": "DB状态",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 2 },
   "targets": [
    {
     "expr": "sort_desc(dic_db_status{job=\"$application\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "熔断状态",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "dic_hystrix_circuit_status{job=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(1- disk_free{job=\"$application\", instance=\"$instance\"}/disk_total{job=\"$application\", instance=\"$instance\"}) * 100"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Run Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dic_job_run_time_max{job=\"$application\", instance=\"$instance\"} / 1000",
     "legendFormat": "{{name}} + {{cron}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 21, "w": 3, "x": 21, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dic_http_request_total{job=\"$application\", instance=\"$instance\", code!=\"200\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dic_http_request_total{job=\"$application\", instance=\"$instance\"}[30s])",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "dic_http_response_time_min{code=\"200\", job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "MIN : {{url}}"
    },
    {
     "expr": "dic_http_response_time_avg{code=\"200\", job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "AVG : {{url}}"
    },
    {
     "expr": "dic_http_response_time_max{code=\"200\", job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "MAX : {{url}}"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "mem{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "mem"
    },
    {
     "expr": "mem_free{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "mem_used"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "heap{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "heap_committed{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "heap_used{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "nonheap{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "nonheap"
    },
    {
     "expr": "nonheap_committed{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "nonheap_committed"
    },
    {
     "expr": "nonheap_used{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "nonheap_used"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "dic_cpu_usage{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "systemload_average{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "systemload_average"
    },
    {},
    {
     "expr": "processors{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "threads{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "live"
    },
    {
     "expr": "threads_daemon{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "threads_peak{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "threads_totalStarted{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "totalStarted"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_scavenge_count{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "gc_ps_scavenge_count"
    },
    {
     "expr": "gc_ps_marksweep_count{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "gc_ps_marksweep_count"
    }
   ]
  },
  {
   "title": "Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gc_ps_scavenge_time{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "gc_ps_scavenge_time"
    },
    {
     "expr": "gc_ps_marksweep_time{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "gc_ps_marksweep_time"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Classes loaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "classes_loaded{job=\"$application\", instance=\"$instance\"}",
     "legendFormat": "loaded"
    }
   ]
  },
  {
   "title": "Class delta (5m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(classes_loaded{job=\"$application\",instance=\"$instance\"}[5m])",
     "legendFormat": "delta"
    }
   ]
  }
 ]
}