
#[PERSISTENT-VOLUME-CLAIN]
#0_generic_[PersistentVolumeClaim].yml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #IMPORTANTE: Este nombre sera el REUTILIZADO. 
  name: microservicio-employee-pvc
  namespace: default
  labels:
    app: microservicio-employee-service
    role: backend
    stage: production
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #IMPORTANTE: Este nombre sera el REUTILIZADO. 
  name:  microservicio-department-pvc
  namespace: default
  labels:
    app: microservicio-department-service
    role: backend
    stage: production
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #IMPORTANTE: Este nombre sera el REUTILIZADO. 
  name: microservicio-organization-pvc
  namespace: default
  labels:
    app: microservicio-organization-service
    role: backend
    stage: production
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #IMPORTANTE: Este nombre sera el REUTILIZADO. 
  name: microservicio-utl-capadb-pvc
  namespace: default
  labels:
    app: microservicio-utl-capadb-service
    role: backend
    stage: production
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  #IMPORTANTE: Este nombre sera el REUTILIZADO. 
  name: filebeat-pvc
  namespace: default
  labels:
    app: filebeat
    role: backend
    stage: production
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  
  
 
  