
#[SEGURIDAD: ROLE / ROLEBINDING]
#IMPORTANTE, [spring-cloud-kubernetes] NO tiene acceso a la API de KUBERNETES para leer 'ConfigMaps'. Para ello se debe ejecutar estos scripts. 
#0_generic_[Seguridad_Rol].yml

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1 
kind: RoleBinding
metadata:
  name: namespace-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""

  